### ISSUE TITLE
Panic when adding music dir

### ISSUE THREAD

**Issue by brian6932** [zX3no/gonk#23] opened 2022-10-26 20:57 UTC
```
❯ gonk add D:\Music
thread '<unnamed>' panicked at '"D:\\Music\\DRAGON_BALL_SUPER_OST\\DRAGON_BALL_SUPER_OST\\[180228] 住友紀人 - ドラゴンボール超 オリジナルサウンドトラック -Vol.2- (flac)\\Disc 1\\27 限界突破.flac"', gonk-core\src\lib.rs:687:23
stack backtrace:
   0:     0x7ff6485e73c2 - <unknown>
   1:     0x7ff6486002ab - <unknown>
   2:     0x7ff6485e344a - <unknown>
   3:     0x7ff6485e710b - <unknown>
   4:     0x7ff6485e9de9 - <unknown>
   5:     0x7ff6485e9a6a - <unknown>
   6:     0x7ff6484e6ff7 - <unknown>
   7:     0x7ff6485ea6a0 - <unknown>
   8:     0x7ff6485ea3fd - <unknown>
   9:     0x7ff6485e7def - <unknown>
  10:     0x7ff6485ea0c0 - <unknown>
  11:     0x7ff648615b15 - <unknown>
  12:     0x7ff6485304a8 - <unknown>
  13:     0x7ff648546658 - <unknown>
  14:     0x7ff648546f91 - <unknown>
  15:     0x7ff64854c742 - <unknown>
  16:     0x7ff648544059 - <unknown>
  17:     0x7ff64854708e - <unknown>
  18:     0x7ff64854c742 - <unknown>
  19:     0x7ff648544059 - <unknown>
  20:     0x7ff64854708e - <unknown>
  21:     0x7ff64854c742 - <unknown>
  22:     0x7ff648544059 - <unknown>
  23:     0x7ff64854708e - <unknown>
  24:     0x7ff64854c742 - <unknown>
  25:     0x7ff648544059 - <unknown>
  26:     0x7ff64854708e - <unknown>
  27:     0x7ff64854c742 - <unknown>
  28:     0x7ff648544059 - <unknown>
  29:     0x7ff64854708e - <unknown>
  30:     0x7ff64854c742 - <unknown>
  31:     0x7ff648544059 - <unknown>
  32:     0x7ff64854708e - <unknown>
  33:     0x7ff64853367e - <unknown>
  34:     0x7ff648612808 - <unknown>
  35:     0x7ff6485ca6e1 - <unknown>
  36:     0x7ff6485cf383 - <unknown>
  37:     0x7ff6485cd246 - <unknown>
  38:     0x7ff6485ee97c - <unknown>
  39:     0x7ffa5c14117e - BaseThreadInitThunk
  40:     0x7ffa5dfe42db - RtlUserThreadStart
```
I'm guessing it has to do with it having unicode Japanese chars 🤷
Ver: gonk v0.2.0 (built with: cargo +nightly install --git https://github.com/zX3no/gonk.git)
Happens with the v0.12 bin as well

**Comment by zfphex** [comment] 2022-10-27 03:29
I had a quick look and it seems the Symphonia is unable to decode the song (unicode should work fine). I didn't log the error for some reason, so I've changed that. 

Could you run this again on the latest commit and tell me what error you get?
Also, if you could link me the file it might help fix the issue.

Thanks!

**Comment by brian6932** [comment] 2022-10-27 09:21
<details>
  <summary>logs</summary>

```
Brian ~  16.334s
❯ cargo +nightly install --git https://github.com/zX3no/gonk.git
    Updating git repository `https://github.com/zX3no/gonk.git`
  Installing gonk v0.2.0 (https://github.com/zX3no/gonk.git#e1aed0ef)
    Updating crates.io index
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling log v0.4.17
   Compiling bitflags v1.3.2
   Compiling encoding_rs v0.8.31
   Compiling scopeguard v1.1.0
   Compiling winapi v0.3.9
   Compiling arrayvec v0.7.2
   Compiling bytemuck v1.12.1
   Compiling lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.12
   Compiling windows_x86_64_msvc v0.42.0
   Compiling rayon-core v1.9.3
   Compiling parking_lot_core v0.9.4
   Compiling smallvec v1.10.0
   Compiling num_cpus v1.13.1
   Compiling either v1.8.0
   Compiling memmap2 v0.5.7
   Compiling cassowary v0.3.0
   Compiling unicode-segmentation v1.10.0
   Compiling unicode-width v0.1.10
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.11
   Compiling lock_api v0.4.9
   Compiling rayon v1.5.3
   Compiling windows-sys v0.42.0
   Compiling symphonia-core v0.5.1
   Compiling crossbeam-channel v0.5.6
   Compiling crossbeam-deque v0.8.2
   Compiling symphonia-metadata v0.5.1
   Compiling symphonia-utils-xiph v0.5.1
   Compiling symphonia-bundle-mp3 v0.5.1
   Compiling symphonia-format-ogg v0.5.1
   Compiling symphonia-bundle-flac v0.5.1
   Compiling symphonia-codec-vorbis v0.5.1
   Compiling parking_lot v0.12.1
   Compiling symphonia v0.5.1
   Compiling winapi-util v0.1.5
   Compiling crossterm_winapi v0.9.0
   Compiling same-file v1.0.6
   Compiling crossterm v0.25.0
   Compiling walkdir v2.3.2
   Compiling gonk-core v0.2.0 (~\scoop\persist\rustup-msvc\.cargo\git\checkouts\gonk-5679db22c8e816e7\e1aed0e\gonk-core)
   Compiling gonk-player v0.2.0 (~\scoop\persist\rustup-msvc\.cargo\git\checkouts\gonk-5679db22c8e816e7\e1aed0e\gonk-player)
   Compiling tui v0.19.0
   Compiling gonk v0.2.0 (~\scoop\persist\rustup-msvc\.cargo\git\checkouts\gonk-5679db22c8e816e7\e1aed0e\gonk)
    Finished release [optimized] target(s) in 13.51s
  Installing ~\scoop\persist\rustup-msvc\.cargo\bin\gonk.exe
   Installed package `gonk v0.2.0 (https://github.com/zX3no/gonk.git#e1aed0ef)` (executable `gonk.exe`)
Brian ~  3.059s
❯ gonk add D:\Music
thread '<unnamed>' panicked at 'Probe error: unsupported feature: core (probe): no suitable format reader found @ path: D:\Music\DRAGON_BALL_SUPER_OST\DRAGON_BALL_SUPER_OST\[180228] 住友紀人 - ドラゴンボール超 オリジナルサウンドトラック -Vol.2- (flac)\Disc 1\27 限界突破.flac', gonk-core\src\lib.rs:687:25
stack backtrace:
   0:     0x7ff607417272 - <unknown>
   1:     0x7ff60743015b - <unknown>
   2:     0x7ff60741330a - <unknown>
   3:     0x7ff607416fbb - <unknown>
   4:     0x7ff607419c99 - <unknown>
   5:     0x7ff60741991a - <unknown>
   6:     0x7ff607316ff7 - <unknown>
   7:     0x7ff60741a550 - <unknown>
   8:     0x7ff60741a2ad - <unknown>
   9:     0x7ff607417c9f - <unknown>
  10:     0x7ff607419f70 - <unknown>
  11:     0x7ff6074459c5 - <unknown>
  12:     0x7ff607360411 - <unknown>
  13:     0x7ff607376518 - <unknown>
  14:     0x7ff607376e6b - <unknown>
  15:     0x7ff60737c622 - <unknown>
  16:     0x7ff60737390d - <unknown>
  17:     0x7ff607376f64 - <unknown>
  18:     0x7ff60737c622 - <unknown>
  19:     0x7ff60737390d - <unknown>
  20:     0x7ff607376f64 - <unknown>
  21:     0x7ff60737c622 - <unknown>
  22:     0x7ff60737390d - <unknown>
  23:     0x7ff607376f64 - <unknown>
  24:     0x7ff60737c622 - <unknown>
  25:     0x7ff60737390d - <unknown>
  26:     0x7ff607376f64 - <unknown>
  27:     0x7ff60737c622 - <unknown>
  28:     0x7ff60737390d - <unknown>
  29:     0x7ff607376f64 - <unknown>
  30:     0x7ff60737c622 - <unknown>
  31:     0x7ff60737390d - <unknown>
  32:     0x7ff607376f64 - <unknown>
  33:     0x7ff6073636fe - <unknown>
  34:     0x7ff6074426b8 - <unknown>
  35:     0x7ff6073fa5a1 - <unknown>
  36:     0x7ff6073ff243 - <unknown>
  37:     0x7ff6073fd106 - <unknown>
  38:     0x7ff60741e82c - <unknown>
  39:     0x7ffa5c14117e - BaseThreadInitThunk
  40:     0x7ffa5dfe42db - RtlUserThreadStart
  ```
  
  </details>
 
  @zX3no

**Comment by zfphex** [comment] 2022-10-27 10:08
I'm fairly sure that the file is either not being loaded correctly or is corrupted. 
Music formats usually have a byte sequence idenetifying the format ("fLaC" for FLAC), but Symphonia isn't able to find it. I didn't write the decoder so I'm not really sure if that's the issue.
I even download what I think is the same file (could be different I got it off `nyaa`) and I still don't get any issue.

I do have a FLAC decoder in the works. #24 has some of the basics but it's not finished yet.

I'll change the way files are scanned and log how many couldn't be processed, then at least some of your files will work.

In the meantime, have you tried addding music without that album or song? Do you get the same error for all files or just a few?

If you could link the file that would help a lot!

**Comment by brian6932** [comment] 2022-10-27 10:35
Sure I can try that

**Comment by zfphex** [comment] 2022-10-27 10:45
I just added some logging in the latest commit, so gonk shouldn't crash when you scan for files. 

You can find a log with errors in: `C:\Users\User_Name\AppData\Roaming\gonk\gonk.log`

**Comment by brian6932** [comment] 2022-10-27 11:05
(I haven't moved the file yet, but I did get a new panic after updating)

<details>
  <summary>panic</summary>
  
```
Brian ~
❯ cargo +nightly install --git https://github.com/zX3no/gonk.git
    Updating git repository `https://github.com/zX3no/gonk.git`
  Installing gonk v0.2.0 (https://github.com/zX3no/gonk.git#cc885ad7)
    Updating crates.io index
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling bitflags v1.3.2
   Compiling log v0.4.17
   Compiling encoding_rs v0.8.31
   Compiling arrayvec v0.7.2
   Compiling lazy_static v1.4.0
   Compiling bytemuck v1.12.1
   Compiling winapi v0.3.9
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.12
   Compiling windows_x86_64_msvc v0.42.0
   Compiling rayon-core v1.9.3
   Compiling parking_lot_core v0.9.4
   Compiling smallvec v1.10.0
   Compiling num_cpus v1.13.1
   Compiling either v1.8.0
   Compiling memmap2 v0.5.7
   Compiling unicode-width v0.1.10
   Compiling cassowary v0.3.0
   Compiling unicode-segmentation v1.10.0
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.11
   Compiling lock_api v0.4.9
   Compiling rayon v1.5.3
   Compiling windows-sys v0.42.0
   Compiling symphonia-core v0.5.1
   Compiling crossbeam-channel v0.5.6
   Compiling crossbeam-deque v0.8.2
   Compiling symphonia-metadata v0.5.1
   Compiling symphonia-utils-xiph v0.5.1
   Compiling symphonia-bundle-mp3 v0.5.1
   Compiling symphonia-format-ogg v0.5.1
   Compiling symphonia-bundle-flac v0.5.1
   Compiling symphonia-codec-vorbis v0.5.1
   Compiling symphonia v0.5.1
   Compiling parking_lot v0.12.1
   Compiling winapi-util v0.1.5
   Compiling crossterm_winapi v0.9.0
   Compiling same-file v1.0.6
   Compiling crossterm v0.25.0
   Compiling walkdir v2.3.2
   Compiling gonk-core v0.2.0 (~\scoop\persist\rustup-msvc\.cargo\git\checkouts\gonk-5679db22c8e816e7\cc885ad\gonk-core)
   Compiling gonk-player v0.2.0 (~\scoop\persist\rustup-msvc\.cargo\git\checkouts\gonk-5679db22c8e816e7\cc885ad\gonk-player)
   Compiling tui v0.19.0
   Compiling gonk v0.2.0 (~\scoop\persist\rustup-msvc\.cargo\git\checkouts\gonk-5679db22c8e816e7\cc885ad\gonk)
    Finished release [optimized] target(s) in 13.99s
   Replacing ~\scoop\persist\rustup-msvc\.cargo\bin\gonk.exe
    Replaced package `gonk v0.2.0 (https://github.com/zX3no/gonk.git#e1aed0ef)` with `gonk v0.2.0 (https://github.com/zX3no/gonk.git#cc885ad7)` (executable `gonk.exe`)
Brian ~  14.435s
❯ gonk add D:\Music
thread '<unnamed>' panicked at 'Could not open file.: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', gonk-core\src\lib.rs:659:46
stack backtrace:
   0:     0x7ff7161499f2 - <unknown>
   1:     0x7ff7161628db - <unknown>
   2:     0x7ff716145a8a - <unknown>
   3:     0x7ff71614973b - <unknown>
   4:     0x7ff71614c419 - <unknown>
   5:     0x7ff71614c09a - <unknown>
   6:     0x7ff71603bf07 - <unknown>
   7:     0x7ff71614ccd0 - <unknown>
   8:     0x7ff71614ca2d - <unknown>
   9:     0x7ff71614a41f - <unknown>
  10:     0x7ff71614c6f0 - <unknown>
  11:     0x7ff716178985 - <unknown>
  12:     0x7ff716178c23 - <unknown>
  13:     0x7ff716090d5e - <unknown>
  14:     0x7ff716094766 - <unknown>
  15:     0x7ff7160a9e2b - <unknown>
  16:     0x7ff7160a3242 - <unknown>
  17:     0x7ff71609c551 - <unknown>
  18:     0x7ff7160a9f1b - <unknown>
  19:     0x7ff7160a21e2 - <unknown>
  20:     0x7ff71609c437 - <unknown>
  21:     0x7ff7160a9f1b - <unknown>
  22:     0x7ff7160a3242 - <unknown>
  23:     0x7ff71609c551 - <unknown>
  24:     0x7ff7160a9f1b - <unknown>
  25:     0x7ff7160a21e2 - <unknown>
  26:     0x7ff71609c437 - <unknown>
  27:     0x7ff7160a9f1b - <unknown>
  28:     0x7ff7160a21e2 - <unknown>
  29:     0x7ff71609c437 - <unknown>
  30:     0x7ff7160a9f1b - <unknown>
  31:     0x7ff7160a21e2 - <unknown>
  32:     0x7ff71609c437 - <unknown>
  33:     0x7ff7160a9f1b - <unknown>
  34:     0x7ff716092065 - <unknown>
  35:     0x7ff7160a2902 - <unknown>
  36:     0x7ff7160a52d7 - <unknown>
  37:     0x7ff716175678 - <unknown>
  38:     0x7ff71612ce41 - <unknown>
  39:     0x7ff716131753 - <unknown>
  40:     0x7ff71612f616 - <unknown>
  41:     0x7ff716150fac - <unknown>
  42:     0x7ffc8272117e - BaseThreadInitThunk
  43:     0x7ffc833642db - RtlUserThreadStart
```

</details>

I'll try moving it out now
After moving the file, I still get this panic
There's no `gonk.log` in `~\AppData\Roaming\gonk` yet

**Comment by brian6932** [comment] 2022-10-27 11:13
> If you could link the file that would help a lot!

https://i.alienpls.org/Kzr

**Comment by zfphex** [comment] 2022-10-27 11:14
Thanks! I'm looking into it.
Edit: Just confirmed that the file is not the problem.

**Comment by zfphex** [comment] 2022-10-27 11:19
I somehow missed an unwrap when opening files. It's fixed now so it *hopefully* won't crash.
Do you have the file open in another program because sometimes that causes 'Access is denied.' errors?

**Comment by brian6932** [comment] 2022-10-27 11:21
Nice after updating the panic is gone

**Comment by zfphex** [comment] 2022-10-27 11:21
Nice! Are your files missing though?

**Comment by brian6932** [comment] 2022-10-27 11:24
@zX3no this is the log file: https://i.alienpls.org/FXm.log
I'll run a take own to see if the access is denied fixes
Edit: Take owning didn't work

**Comment by brian6932** [comment] 2022-10-27 11:35
Small question, how do you exit out of search? using `/` again or `esc` doesn't seem to be able to do it

**Comment by zfphex** [comment] 2022-10-27 11:38
You can use `tab` to exit out of search. Escape is used for clearing the search bar. Now that I think about it though there is already `shift+backspace & backspace` so it doesn't make much sense.

I'll probably rework the binds at some point (`,` and `.` are quite bad). You might notice that there's no way to swap back to the page you were previously on. Using tab in the search always goes back to the queue, same with the settings.

**Comment by brian6932** [comment] 2022-10-27 11:42
yea I deleted it, cause I figured it out 😄

**Comment by zfphex** [comment] 2022-10-27 11:55
I'll get around to it I've just been busy lately.

Looking over your logs. I understand some of the errors (limitations of the decoding library I'm using), but some don't make sense. 
The file you gave me worked fine, which shouldn't be the case. ¯\\_(ツ)_/¯

Thanks for your help anyway.

**Closed as completed** 2022-10-27 11:56 UTC
Labels: bug
